// Interface text of the report, in English and Russian.
// (The findings themselves live in src/i18n.ts, shared with the CLI.)

import type { Lang } from '../../types.ts';

const UI_EN = {
  kicker: 'Geological survey of a code repository',
  columnTitle: 'Stratigraphic column · code alive at HEAD',
  notesTitle: 'Field notes',
  strataTitle: 'Stratigraphy',
  strataLede: 'Every line alive at each moment, coloured by the period it was written in. Lower layers are older. When a layer thins, its code was rewritten or deleted; a layer that keeps its thickness is bedrock. Switch to layers by author to watch ownership change hands, or pick one module.',
  mapTitle: 'Geological map',
  scrub: 'Moment in history', play: 'Play history', pause: 'Pause',
  findFile: 'Find file', findPlaceholder: 'type a path…', borehole: 'Borehole', inLastYear: 'in the last 12 months', born: 'first surviving line', owners: 'Who wrote today’s lines', changesWith: 'Changes together with (share of this file’s commits)', noPartners: 'No strong temporal coupling.', close: 'Close',
  layers: 'Layers', layersBy: { period: 'by period', author: 'by author' }, moduleLabel: 'Module', coreSample: 'core sample, old → new',
  mapLede: 'Each tile is a file, sized by its lines. Colour by the age of its median line, by hotspot score, by who owns it, by knowledge at risk, or by recent change. Click a folder to zoom in, click a file to drill a borehole into it.',
  colorBy: 'Colour by',
  modes: { age: 'Age', hot: 'Hotspots', owner: 'Owner', orphan: 'Knowledge at risk', churn: 'Recent change' },
  hlTitle: 'Half-life',
  hlLede: 'Kaplan–Meier survival of individual lines: the share of lines still unchanged after a given age. Lines still alive today count as censored observations, so young code does not skew the estimate. The dot marks the half-life.',
  hotTitle: 'Hotspots',
  hotLede: 'Change frequency against indentation complexity. Files in the upper right are complex and keep changing: the best places to spend refactoring effort. Bubble size is lines of code.',
  faultTitle: 'Fault lines',
  faultLede: 'Temporal coupling: modules and files that change in the same commits. Strong coupling across module boundaries often means a hidden dependency or a leaky abstraction. Mass commits touching more than {max} files are ignored.',
  knowTitle: 'Knowledge & bus factor',
  knowLede: 'Who wrote the lines that exist today. Bus factor is the smallest number of people who together wrote more than half of a module. “At risk” is code written by people inactive for more than a year.',
  fossilTitle: 'Fossil record',
  fossilLede: 'The oldest non-trivial lines that survive unchanged at HEAD.',
  eventsTitle: 'Extinctions & big bangs',
  eventsLede: 'Commits that removed the most code older than a year, and commits that added the most lines at once.',
  extinctions: 'Extinctions', bigBangs: 'Big bangs',
  seisTitle: 'Seismograph',
  seisLede: 'Weekly commit activity (trace) and the number of people active each month (shaded).',
  lines: 'lines', files: 'files', commits: 'commits', people: 'people', surveyed: 'surveyed', head: 'HEAD', branch: 'branch',
  written: 'written', alive: 'alive', survived: 'survived', total: 'total', share: 'share',
  age: 'age', medianLine: 'median line', owner: 'owner', revs: 'changes', revsShort: 'changes', recentRevs: 'changes, last 12 months', complexity: 'complexity', loc: 'LOC',
  bus: 'bus factor', atRisk: 'at risk', meanAge: 'mean age', module: 'module', file: 'file', person: 'person', active: 'active', inactive: 'inactive', status: 'status', firstLast: 'active span',
  pair: 'file pair', shared: 'together', degree: 'degree', lastChange: 'last change', authors: 'authors', role: 'role',
  unconformity: 'unconformity: nothing survives', allAges: 'all lines', yearsAxis: 'age of line',
  noData: 'Not enough history for this plate.', other: 'others', bots: 'bots',
  methodTitle: 'Method', method: 'Strata replays the first-parent history with git log -p -U0 and tracks, for every line, the commit that wrote it — using hunk headers only. At HEAD this reproduces git blame --first-parent. Lines brought in by merges are credited to the side-branch commit that changed that file most.',
  diagTitle: 'Survey diagnostics', excludedTitle: 'Excluded', excludedText: '{n} path patterns (lockfiles, vendored, generated, minified code).',
  diag: 'Surveyed in {s}s with git {g}. Hunk repairs: {r}. Files whose replayed length differs from HEAD: {m}.',
  zoomOut: 'whole repository', clickZoom: 'click to zoom',
  roles: { source: 'source', tests: 'tests', docs: 'docs', 'config & tooling': 'config & tooling' },
  hotLegend: 'cool → hot', orphanLegend: 'share of lines by people inactive > 1 year', churnLegend: 'changes in the last 12 months',
  merge: 'merge', meanAgeRemoved: 'mean age removed', byWeek: 'commits per week', activePeople: 'active people per month',
};

/** Every UI string; the Russian table must have exactly the same keys. */
export type UiStrings = typeof UI_EN;

const UI_RU: UiStrings = {
  kicker: 'Геологическая съёмка репозитория кода',
  columnTitle: 'Стратиграфическая колонка · живой код на HEAD',
  notesTitle: 'Полевые заметки',
  strataTitle: 'Стратиграфия',
  strataLede: 'Все живые строки в каждый момент времени, окрашенные по периоду, когда они были написаны. Нижние слои старше. Если слой истончается, его код переписали или удалили; слой, сохраняющий толщину, — коренная порода. Переключите слои на авторов, чтобы увидеть смену владельцев, или выберите один модуль.',
  mapTitle: 'Геологическая карта',
  scrub: 'Момент истории', play: 'Проиграть историю', pause: 'Пауза',
  findFile: 'Найти файл', findPlaceholder: 'начните вводить путь…', borehole: 'Скважина', inLastYear: 'за последние 12 месяцев', born: 'первая уцелевшая строка', owners: 'Кто написал сегодняшние строки', changesWith: 'Меняется вместе с (доля коммитов этого файла)', noPartners: 'Сильных временных связей нет.', close: 'Закрыть',
  layers: 'Слои', layersBy: { period: 'по периоду', author: 'по автору' }, moduleLabel: 'Модуль', coreSample: 'керн, старое → новое',
  mapLede: 'Каждый прямоугольник — файл, площадь пропорциональна числу строк. Цвет — возраст медианной строки, индекс горячей точки, владелец, знание под угрозой или недавние изменения. Нажмите на папку, чтобы приблизить, на файл — чтобы пробурить в нём скважину.',
  colorBy: 'Цвет',
  modes: { age: 'Возраст', hot: 'Горячие точки', owner: 'Владелец', orphan: 'Знание под угрозой', churn: 'Недавние изменения' },
  hlTitle: 'Период полураспада',
  hlLede: 'Кривая выживаемости Каплана–Мейера для отдельных строк: доля строк, ещё не изменённых к заданному возрасту. Живые сегодня строки учитываются как цензурированные наблюдения, поэтому молодой код не искажает оценку. Точка — период полураспада.',
  hotTitle: 'Горячие точки',
  hotLede: 'Частота изменений против сложности по отступам. Файлы справа вверху сложны и постоянно меняются — лучшие кандидаты на рефакторинг. Размер пузыря — число строк.',
  faultTitle: 'Линии разломов',
  faultLede: 'Временная связность: модули и файлы, которые меняются в одних и тех же коммитах. Сильная связь через границы модулей часто означает скрытую зависимость или протекающую абстракцию. Массовые коммиты, затрагивающие больше {max} файлов, не учитываются.',
  knowTitle: 'Знание и bus factor',
  knowLede: 'Кто написал строки, существующие сегодня. Bus factor — наименьшее число людей, вместе написавших больше половины модуля. «Под угрозой» — код людей, неактивных больше года.',
  fossilTitle: 'Палеонтологическая летопись',
  fossilLede: 'Самые старые нетривиальные строки, дожившие до HEAD без изменений.',
  eventsTitle: 'Вымирания и большие взрывы',
  eventsLede: 'Коммиты, удалившие больше всего кода старше года, и коммиты, добавившие больше всего строк за раз.',
  extinctions: 'Вымирания', bigBangs: 'Большие взрывы',
  seisTitle: 'Сейсмограф',
  seisLede: 'Коммиты по неделям (трасса) и число активных людей по месяцам (заливка).',
  lines: 'строк', files: 'файлов', commits: 'коммитов', people: 'человек', surveyed: 'съёмка', head: 'HEAD', branch: 'ветка',
  written: 'написано', alive: 'живо', survived: 'уцелело', total: 'всего', share: 'доля',
  age: 'возраст', medianLine: 'медианная строка', owner: 'владелец', revs: 'изменений', revsShort: 'изменений', recentRevs: 'изменений за 12 месяцев', complexity: 'сложность', loc: 'строк',
  bus: 'bus factor', atRisk: 'под угрозой', meanAge: 'средний возраст', module: 'модуль', file: 'файл', person: 'человек', active: 'активен', inactive: 'неактивен', status: 'статус', firstLast: 'период активности',
  pair: 'пара файлов', shared: 'вместе', degree: 'степень', lastChange: 'последнее изменение', authors: 'авторов', role: 'роль',
  unconformity: 'несогласие: ничего не сохранилось', allAges: 'все строки', yearsAxis: 'возраст строки',
  noData: 'Недостаточно истории для этой таблицы.', other: 'остальные', bots: 'боты',
  methodTitle: 'Метод', method: 'Strata воспроизводит историю по первым родителям через git log -p -U0 и для каждой строки отслеживает коммит, который её написал, — только по заголовкам хунков. На HEAD это совпадает с git blame --first-parent. Строки, пришедшие через слияния, приписываются коммиту боковой ветки, сильнее всего менявшему этот файл.',
  diagTitle: 'Диагностика съёмки', excludedTitle: 'Исключено', excludedText: '{n} шаблонов путей (lock-файлы, вендоринг, сгенерированный и минифицированный код).',
  diag: 'Съёмка заняла {s} с, git {g}. Ремонтов хунков: {r}. Файлов, чья длина после реплея расходится с HEAD: {m}.',
  zoomOut: 'весь репозиторий', clickZoom: 'нажмите, чтобы приблизить',
  roles: { source: 'исходники', tests: 'тесты', docs: 'документация', 'config & tooling': 'конфиги и инструменты' },
  hotLegend: 'холодно → горячо', orphanLegend: 'доля строк людей, неактивных > 1 года', churnLegend: 'изменений за последние 12 месяцев',
  merge: 'слияние', meanAgeRemoved: 'ср. возраст удалённого', byWeek: 'коммитов в неделю', activePeople: 'активных людей в месяц',
};

export const UI: Record<Lang, UiStrings> = { en: UI_EN, ru: UI_RU };
